<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-12-15 06:12+0000
// PO revision date:  2012-12-14 06:05+0000
$lang = array(
	'lang' => 'es_AR',
	'sitio_web' => 'Sitio Web',
	'tipo_de_contexto' => 'Tipo de contexto'
);
